### ISSUE TITLE
Input games from elsewhere

### ISSUE THREAD

**Issue by Twixtfanatic** [stevens68/twixtbot-ui#103]
If I try to manually enter into Twixtbot the moves of a game where swap was played, I do not see a swap button for me to click, even though such a button does appear when I am playing against the bot. Did I miss something?

It would be nice if the ui would include an option in the menu to import games from sources beyond Little Golem. For example, the following format is common.

1.f6 2.swap 3.m16 4.n11 5.p11 6.r11 7.r12 8.p10 9.s10 10.r6 11.k11 12.k8 13.i7 14.j6 15.j9 16.h5 17.t6 18.t7 19.l8 20.n4 21.n6 22.m6 23.l7 24.k7 25.o4 26.m8 27.o7 28.o9 29.s9 30.q4 31.r2 32.s3 33.resign

Or is this possible already?

Thanks for your attention.

**Comment by stevens68** [comment]
Hi, thanks for your comment.
You can manually swap by clicking the first peg again. You can also prepare and load a T1J-like  file that has a swap move. See [README.md](https://github.com/stevens68/twixtbot-ui#readme) file. 
Regards, stevens68
