### ISSUE TITLE
Cannot see GUI on Windows (only in task bar preview)

### ISSUE THREAD

**Issue by Dillxn** [stevens68/twixtbot-ui#105]
First, what a wonderful project this is. I have been looking for a way to play against an advanced AI, so thank you!

My issue is that after successfully installing TwixTBot-UI (manual install) with no errors, I am able to launch the program as described in the Readme.md; however, only the python logo shows up in my task bar, and nothing on screen. I can hover over the taskbar item and see a window preview of the GUI, but I cannot get it to show an actual window. I have tried the 'move' action on right-click to no avail.

Additionally, I was going to try the Windows installer but the link is now broken.

Thank you again.

**Comment by Dillxn** [comment]
Okay, I was able to solve it by pressing the down arrow key after clicking 'move (window)' and then moving my cursor... 

However the GUI seems non-resizable and is taller than my 4k monitor. I don't see an option in config to change window height.

**Comment by stevens68** [comment]
Hi Dillxn,
thanks for using twixtbot-ui, Sorry for the late reply. 
I haven't testet the GUI with latest Python versions. Maybe you can send the version you are using.
I also re-enabled the link to the Windows installer. You might want to try to download it again.

The Window is re-sizeable only via the board_size settings. The biggest is 800 pixels (default is 600 pixel).

If this is not sufficient you might want to add bigger values in src/constants.py:

`# settings
BOARD_SIZE_LIST = [500, 600, 700, 800, 1000, 1200]
`

...and restart and see what happens

Thanks for your feedback!
