### ISSUE TITLE
recognize a draw

### ISSUE THREAD

**Issue by Twixtfanatic** [stevens68/twixtbot-ui#106]
Draws are rare, but when they happen, IMO the gui should recognize it and allow the user to end the game when playing against the bot. I am attaching the file draw.T1 which is a game that might end once all the holes are filled up, but I'm not interested in finding out.
[draw.T1.tar.gz](https://github.com/stevens68/twixtbot-ui/files/12671009/draw.T1.tar.gz)
Thank you. EDIT I should add, the bot played black.

**Comment by stevens68** [comment]
Hi,

thanks for your feedback! 
Yes, draw detection would be a nice feature. It's a little tricky to detect a draw though, but I have some ideas.
Just have to find some time to work on it.

Regards

**Comment by stevens68** [comment]
Hi,
implemeted Draw Check; you might want to try it. I added your draw example (shortened game) to the games folder; See also README.md section 'Draw'.

Thanks for using twixtbot-ui!

[PR#110](https://github.com/stevens68/twixtbot-ui/pull/110)
