### ISSUE TITLE
Undo of first move

### ISSUE THREAD

**Issue by stevens68** [stevens68/twixtbot-ui#11]
Undo of first move doesn't work and leads to inconsistent state, and crash

**Comment by agtoever** [comment]
I have also seen this "sometimes, but as far as I can tell, I haven't be able to consistently reproduce this. Do you?

**Comment by stevens68** [comment]
...I can consistently reproduce it when I load sample games from folder ./games and try to undo all moves

**Comment by stevens68** [comment]
fixed in PR#21
