### ISSUE TITLE
Indicate current best move / heatmap / game analyzer

### ISSUE THREAD

**Issue by stevens68** [stevens68/twixtbot-ui#16]
In addition to the bar plot, we should see the current best move on the board (incl. links). The peg and links should be highlights/or dotted.

**Comment by agtoever** [comment]
Suggestion: the backend gives different moves a rating. Instead of showing the single best move, we could color the unoccupied dots based on the MCTS score: shades of green for moves having a positive effect on the MCTS and shades of red having a negative effect.

**Comment by stevens68** [comment]
Good point. I thought about it, too. Not sure if i created an issue for it. (Heat map). Did you also see the issue that somebody added in the twixtbot repo. He presents something similar  I think he is not aware of twixtbot ui yet. Maybe he can join us hereThanks for your bugfix! Regards MVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Albert ten Oever ***@***.***> Datum: 10.03.21  18:28  (GMT+01:00) An: stevens68/twixtbot-ui ***@***.***> Cc: stevens68 ***@***.***>, Author ***@***.***> Betreff: Re: [stevens68/twixtbot-ui] Indicate current best move on board during  MCTS (#16) 
Suggestion: the backend gives different moves a rating. Instead of showing the single best move, we could color the unoccupied dots based on the MCTS score: shades of green for moves having a positive effect on the MCTS and shades of red having a negative effect.

**Comment by genmeblog** [comment]
Hi! Indeed I wasn't aware of this repo. Great stuff!!! I can try to move my experiments here. Yes. heatmap would be very helpful.

**Comment by agtoever** [comment]
@stevens68 : let's talk "how" a bit. I think I might have time this weekend to make it.

- I create a new module "heat map", which contains the heat map data
- We create a button at the bottom ("heat map") that calculates and plots the heat map. I think "turning on" the heat map feature isn't a good idea, since it will take same calculation time, which has a negative impact on UX if we turn it on constantly. Also, from a game experience perspective, having a heat map on all the time, makes the player lazy (I think), which opposes a game where you should take the time to think about the next move.
- After the button is pressed, the heat map object is instantiated and the delta MCTS is calculated for each move. I think the "best" way to do this, is to iterate through all legal moves, simulate that move on the twixt backend object, check the MCTS and undo that move. After calculation, we update all the hole's colosr (in tbui.py) using a Matplotlib colormap
- In TwixtbotUI, we track if the heat map is plotted. If so, the holes are redrawn (in "normal" color) in update_after_move() (this might not be nessecary, if this is already done by self.board.draw() in update_after_move().

Please let me know what you think of this.

**Comment by stevens68** [comment]
thanks for the comment and your PR; I played around with it. Looks nice!
calculating 500+ evals just takes it 's time...
Distribution looks surprisingly smooth in many cases, although P is not smooth in most cases. 

I moved the code to a new branch in my repo. I'll do during the next days
* some "cosmetics" 
* move it to a thread
* re-use the progressbar 
* allow to cancel and display an unfinished heatmap
* use P (descending) as calculation order

**Comment by genmeblog** [comment]
I'm getting strange results or don't understand how heatmap is created. I think colors for the top (say) 5 should be clearly different than the rest. Also something is wrong with sizes for a black player.

![image](https://user-images.githubusercontent.com/38646601/111141056-58aee900-8583-11eb-8cf1-fc713416ee6e.png)
![image](https://user-images.githubusercontent.com/38646601/111141258-a0ce0b80-8583-11eb-8480-be1421433bcc.png)

**Comment by stevens68** [comment]
Hi genmeblog,
thanks for your comment. We have to distinguish
* V: (value-head, -1..1) that expresses the value og the board: 0.353 / 0.617 in your examples
* P: (policy-head, 0..1)  that expesses the value for each legal move; here we display the top 3

agtoever's implementtaion doesn't do a heatmap of the P values (that we already have)
but it calculates V for all legal moves by simulating that move - this is why it is relatively slow.

We could also think about a heatmap based on P; I think that's what you implemented for twixtbot; Then we'd only would have to do 1 single eval call and the colors would match the top-3 values on the right.

But still the question is indeed: If the top P value is  0.499 (N9), why isn't V not much better after we execute the move.
Policy-Head and Value-Head sometimes seem to "disagree"

**Comment by stevens68** [comment]
".....Also something is wrong with sizes for a black player."
Are you referring to the radiuses in the second pic? I think dark blue and big radius means: close to -1 (game is lost)

**Comment by genmeblog** [comment]
Thanks for explanations. Indeed my implementation relied on P and I still think it's valuable.
Heatmap as presented on the second image (even on the first one) doesn't give any guidance for a player - I see bigger and smaller dots with similar color. I propose to use more contrasting palletes and emphasize `n` best moves.

**Comment by agtoever** [comment]
@genmeblog : thanks for your comments. The AlphaZero TwixT policy returns 3 moves with probability (which is what you see in the "Evaluation" section with that horizontal bar plots). My approach for the heat map was to simulate each valid move and observe the difference in probability that the player wins. E.g. if the probability to win before the move is 0.8 and after the move it's 0.9, the heat map shows a +0.1. Of course the Policy moves and probabilities are also useful, but there are only 3 moves for a given board position. Not much to plot. And I don't know if AlphaZero would give a longer list of policy head moves and probabilities...

Of course, the moves indicated by the Policy could be highlighted (e.g. by outlining the green dots with a black line or something). This would visually make the heat map more consistent with that bar plot. I totally agree with that.

Another choice I made was that I scaled the resulting probability delta's for the heat map. If the change in probability ranges from [-0.3 to +0.1], I chose to keep the relative difference of the positive value. In other words, for the colours in the heat map, [-0.3, +0.1] would scale from maximum blue (negative value) to 1/3 green (NOT full green). I did this to show how fragile some of the "best" moves are. I hope this explanation makes sense... So in your second picture, you see a *lot* of blue. This means that whichever move you make, it's really bad. Some moves are less bad, but there are no good (green) moves. I thought this would better reflect your position/chances.

As for aesthetics, totally agree that there could be better colours. I just chose these to prevent visual conflict with red/black. I think we should make the colours in the heat map configurable. 

Finally: the grey point in your first pic indeed seems a bug or something. I'll look into that.

**Comment by genmeblog** [comment]
Thanks! Regarding:

> Of course the Policy moves and probabilities are also useful, but there are only 3 moves for a given board position. Not much to plot. And I don't know if AlphaZero would give a longer list of policy head moves and probabilities...

I might be wrong by I believe this code returns policy probs for whole board https://github.com/genmeblog/twixtbot/blob/master/src/one.py#L35 (this is what I used for my marks)

about the following:

> So in your second picture, you see a lot of blue. This means that whichever move you make, it's really bad. Some moves are less bad, but there are no good (green) moves. 

That's (possibly) true when you play against bot. But when analyzing the game between people, you may want to check what could be the best move in particular situation. People are making errors and what is a lost game for twixtbot, still can be winning game for a human. Also, after playing a little more with twixtbot, certain steps can reverse prediction to the opposite.

My hope with this tool is to be able analyze any game to learn possible recovery strategies in case of playing against people. So what would be important here is to be able to see on the board the set of possible moves. Either taken from P or V policy. Bar charts are good but are not enough if you what to see the patterns on the board. The direction with heatmap is great but would be great to be able to see a clear guidance, not only just global view.

**Comment by agtoever** [comment]
I messed up the colours in the heat map. Corrected that. Also added a black circle around the best 3 moves (matching the moves from the bar chart). See my last commit. I think this really improves it.

**Comment by agtoever** [comment]
> I might be wrong by I believe this code returns policy probs for whole board 
> https://github.com/genmeblog/twixtbot/blob/master/src/one.py#L35 (this is what I used for my marks)

Actually, the Twixt backend evaluates a fixed number of "best" moves.

Number of moves defined in Twixt backend:

https://github.com/stevens68/twixtbot-ui/blob/b014f92f3054d0e7d8f786e38e625db8c618de19/src/backend/twixt.py#L10

This is called here in the eval_game function, which is called from twixt-gui from the bot instances:

https://github.com/stevens68/twixtbot-ui/blob/b014f92f3054d0e7d8f786e38e625db8c618de19/src/backend/nnmcts.py#L213

Sure this could be adjusted, but I suspect that this will have a severe impact on the game performance, because eval_game is called several times. I suspect that evaluating P for the entire board would require some backend tweaking...

**Comment by genmeblog** [comment]
> ` top_ixs = numpy.argsort(self.root.P)[-twixt.MAXBEST:] `

Thanks. For me it looks like only slicing the array, which is already fully filled and evaluated. So I wouldn't expect performance hit.

Sorry to be a complaining guy but take a look at this:

![image](https://user-images.githubusercontent.com/38646601/111600959-2f37cc80-87d2-11eb-9398-03aba28fe28e.png)

These dots are so small and barely visible. Also, they doesn't match P from the right side. I would use the opposite strategy for sizes. Small P/V values - small circle. I'll try to play with it later to propose some different colorsets.

**Comment by stevens68** [comment]
Hi,
thanks for your comments and PRs.

I'd meanwhile vote of using P for a heatmap because of performance and more relevance for the player.
(won't implement the threaded solution with progressbar)

You're right, I introduced twixt.MAXBEST to cut off the best three moves. The backend provides all P values. 

When we switch to a P-Heatmap, we can also replace the Heatmap button with a heatmap setting (integer, default 3) that controls the number of best moves to be displayed in the heatmap.

**Comment by agtoever** [comment]
@genmeblog : you have all the right to be a complaining guy against a sloppy developer. The black circles were accidentally shifted 2 places left. I corrected this and pushed this a few hours ago. 

@stevens68 : I agree with switching to the P. Will you implement this (or can I do something)?

**Comment by stevens68** [comment]
@agtoever: Appreciate if you implement it if you like. I added P already in the return values of eval_game and you can pass 
 the length of P you want: 

```
sc, moves, P = self.bot.nm.eval_game(self.game, <length>)
```

**Comment by agtoever** [comment]
Here is a first concept of the heat map by p-value. You find the code under the [branch 'heat map_by_policy'](https://github.com/agtoever/twixtbot-ui/tree/heatmap_by_policy). Any suggestions and comments are welcome. I still need to cleanup the code (move constants from code to constants.py, etc.) and do some error checking, but it basically works.

<img width="987" alt="Screenshot 2021-03-21 at 11 08 10" src="https://user-images.githubusercontent.com/13528099/111901178-a79ec780-8a36-11eb-823c-812e0faff353.png">

**Comment by genmeblog** [comment]
Looks great. One advice about calculating radius. It's good to use `sqrt` of the visualized value. This way the area of the circle will be proportional to that value.

**Comment by genmeblog** [comment]
With math.sqrt it will look like that:

![image](https://user-images.githubusercontent.com/38646601/111919741-d1cea480-8a8b-11eb-9106-8d20696119b2.png)

**Comment by agtoever** [comment]
Pushed a new version to my branch:

- Cleaned up code. 
- Moved constants to configuration file
- Did some basic errorr checking. 
- Added docstrings.
- Implemented @stevens68's suggestion to use the sqrt (**0.5 instead of importing math). 
 
Please let me know if you find anything.

<img width="987" alt="Screenshot 2021-03-21 at 11 08 10" src="https://user-images.githubusercontent.com/13528099/111921529-612c8580-8a95-11eb-94e0-3becce252eef.png">

**Comment by stevens68** [comment]
Nice! Looks like frog spawn. With the green tadpole to survive ;-)
Didn't find any issues. Thanks!

I agree with genmeblog on using sqrt. 

Just one suggestion regarding the Heatmap button: I'd  keep it but implement it more like a toggle: Once pressed, the heatmap is displayed, and will be displayed after every move. Pressing the button again switches it off.   

But feel free to do a PR now. We can discuss/implement this separately.

**Comment by genmeblog** [comment]
I opt for toggling heatmap too. Just wanted to say, this is just great!

**Comment by agtoever** [comment]
Created issue#35.
After merging the heatmap functionality, I suggest we close this issue.

**Comment by stevens68** [comment]
Functionality available after merging PR#33
Thanks for the good discussion and for the implementation!
