### ISSUE TITLE
Add swap functionality in the GUI

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#17]
Note: need to determine how to handle swaps: Little Golem literary swaps the players. The twixt backend however, swaps the board.

**Comment by stevens68** [comment]
Are you referring to swaps in game files? Yes, that's tricky. 
The GUI and the backend handle swaps by mirroring. 
Easiest way would be to just swap the player names and ignore move #1 in swapped game files

**Comment by agtoever** [comment]
Swapping is already implemented by clicking on the peg of the first move. Closing this.
