### ISSUE TITLE
Allow removal of links

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#18]
In the Twixt rules, player are allowed to remove their own links before playing a peg. This is necessary in rare cases to allow a new link, crossing a previously created link.

**Comment by stevens68** [comment]
right, link removal is not supported. twixtbot was trained without link-removal so like "self-crossing-links=false" this would be another "asymmetric" feature.   Little tricky to implement as well, not the UI part, but carrying link removal info in history; saving and loading; undoing , moves etc.

**Comment by agtoever** [comment]
Ok. Agree and understand.
