### ISSUE TITLE
game analyzer

### ISSUE THREAD

**Issue by genmeblog** [stevens68/twixtbot-ui#20]
Is there an option to provide game analyzer with branching? This was my main idea when I was creating the visuals in fork of original twixtbot.

Having loaded game (or played) I would like to see for every move:

1. Current winning/losing chances
2. Rank of the move (position in the sorted list of NN scores)
3. Heatmap, or marked `n` best moves to try out
4. (optionally) possible game play from given moment (like in here: https://github.com/BonyJordan/twixtbot/issues/1#issuecomment-792780717)

This would be highly beneficial to learn some strategies. Especially in lost real games. What do you think?

**Comment by agtoever** [comment]
Suggest merge with "#16 Indicate current best move on board during  MCTS"

**Comment by stevens68** [comment]
Hi genmeblog, 
thanks for your comments. Valid suggestions. 
agtoever and myself had the idea of a heatmap (point 3) as well but haven't started to implement it.

regarding the other requirements
we could evaluate the "board after next move" when right-clicking on a hole 
we could display the P value and the position in the list of moves in a tooltip, when hovering over the hole
optional peg numbers would be nice as well.

**Comment by stevens68** [comment]
Thanks for the good suggestions!
Let's continue the discussion here:  https://github.com/stevens68/twixtbot-ui/issues/16
