### ISSUE TITLE
can't undo game finished by `resign`

### ISSUE THREAD

**Issue by genmeblog** [stevens68/twixtbot-ui#24]
UI communicates that game is over and nothing changes.

**Comment by stevens68** [comment]
...at least this behaviour it's documented in the README.md ;-)
Agreed: Why should undoing "resign" not be possible.

**Comment by genmeblog** [comment]
Indeed! I haven't noticed it. But for a analysis case it's a must I believe.

**Comment by agtoever** [comment]
I think I [fixed this](agtoever:patch-5)

**Comment by stevens68** [comment]
Merged  PR#34
Thanks agtoever!
