### ISSUE TITLE
Enalbe crossing lines when opening tsgf

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#28]
Opening files from Little Golem means that crossing lines is allowed. Currently, the application does nothing with that fact. I think there are severals ways to handle this:

- Silently enable crossing lines whem opening tsgf files
- Asking the user (yes/no) if they want to enable that
- Notify the user that crossing lines is enabled in the settings

Not sure which option is "the best" though...

**Comment by Twixtfanatic** [comment]
Standard and PP are the two most popular rule sets for Twixt. The original twixtbot was written for Little Golem, and uses PP rules which means it expects a player's own links to cross. So I am surprised to hear that the GUI does not allow this. It is my understanding that an engine as strong as the bot, which follows standard rules with link removal, does not exist yet. Is this correct? The documentation should say what ruleset or rulesets are available.

**Comment by stevens68** [comment]
As the README.md says:

- allow self crossing links is supported, but off by default
- having self-crossing-links off can lead to wrong evaluation in some cases (see also sample game slc-issue.t1j) 
- link removal is not supported; 


we discussed link removal but it would lead to even bigger evaluation issues - unless there is a network that was trained with link removal "on"

in his comment above, agtoever refers to loading games that have self-crossing-links "on" but the ui setting is "off".

**Comment by Twixtfanatic** [comment]
Sorry for misunderstanding the original post. I hope I'm not being annoying, but if the only ruleset implemented so far is PP, why would self crossing links be off by default?

**Comment by stevens68** [comment]
I just don't like self-crossing links very much that's why I switched it off by default
