### ISSUE TITLE
Heatmap as checkbox (not button)

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#35]
Create a "toggle" for the heatmap (instead of a button).

**Comment by stevens68** [comment]
Fine with me! 

I hestitated to suggest it, because a "pure" button row might look nicer. But a checkbox would indeed be more consistent with the auto move toggles.

**Comment by agtoever** [comment]
Added to my master and created a pull request.

**Comment by stevens68** [comment]
Thanks, you are really quick!
Merged to master.
