### ISSUE TITLE
Indicate coordinates when moving mouse on the board

### ISSUE THREAD

**Issue by genmeblog** [stevens68/twixtbot-ui#40]
Can we have guide lines on the board? It would be great.
Also, when I move mouse around additional lines can be shown to indicate selected row/column.

**Comment by agtoever** [comment]
The guidelines are already an option in the settings (menu: File > Settings): General > Guidelines (default: off).

Tracking coordinates is tricky. The Twixt board (a PySimpleGui Graph object) doesn't have a hover callback, which can be used for that. We could trick this by creating a Canvas underneath, but I found several internet posts/questions regarding unstable behavior and bad performance using a similar solution. 

Personally, I'd say this will come with a lot of trouble for something that I would classify as a 'nice to have"...

**Comment by genmeblog** [comment]
Oh, sorry, I've missed the option for guidelines.

If the second one is problematic, let's leave it. It's indeed "nice to have" option.

**Comment by stevens68** [comment]
Implemented optional cursor label in PR#51
