### ISSUE TITLE
Better explain AlphaZero (policy moves, P versus MCTS) in readme.md

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#44]
> A next suggestion would be to add additional text on github or in-game on the difference between P-values and evaluation function.

[source](https://www.littlegolem.net/jsp/forum/topic2.jsp?forum=55&topic=429)

**Comment by stevens68** [comment]
Added some more lines to the README.md but don't want to blow up the README with too much background info. Googleing "AlphaZero",  etc. should do the trick :-)
