### ISSUE TITLE
Improve visibility of whose turn it is

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#45]
> If I could make just one change, it would be to make it easier to see whose move it is.  This would make it easier to follow while watching ‘bot TV’.  One stylish way would be to illuminate the two board sides belonging to that player (or just thicken/brighten the boundary color lines).  A simple square of color somewhere prominent near the board would also help.

[source](https://www.littlegolem.net/jsp/forum/topic2.jsp?forum=55&topic=429)

**Comment by stevens68** [comment]
I think last-move-highlighting + turn indicators should be sufficient to see who's turn it is. 
don't think that stylish illuminations add much value
