### ISSUE TITLE
Explain "smart root" (settings windows) in readme.md

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#46]
> ‘smart root’ MCTS option doesn’t seem to be explained

[source](https://www.littlegolem.net/jsp/forum/topic2.jsp?forum=55&topic=429)

**Comment by stevens68** [comment]
Will remove smart rooot it for now from the Settings dialog. (Actually a leftover from initial versions). 
We might come back to that later as a separate issue, but low prio.

**Comment by stevens68** [comment]
Removed from Settings for now.
