### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#49]
> keyboard shortcuts

[source](https://www.littlegolem.net/jsp/forum/topic2.jsp?forum=55&topic=429)

**Comment by stevens68** [comment]
started to work on this

**Comment by agtoever** [comment]
Comments from add3993 from the Little Golem forum: _I would love shortcuts for the bottom-row buttons; for toggling the heatmap; and for toggling auto-play for one or both players.  Manual move-entry is cumbersome and not too helpful, I agree._

**Comment by stevens68** [comment]
Thanks agtoever. Will implement it accordingly. PR coming up soon.

**Comment by stevens68** [comment]
Implemented in PR#52
