### ISSUE TITLE
Missing dependencies in requirements.txt

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#5]
It seems that PySimpleGUI and Matplotlib are also required, but don't appear in the requirements.txt.

**Comment by agtoever** [comment]
Sorry. My mistake. Messed up python 3.8 and 3.9 running parallel...

**Comment by stevens68** [comment]
Thanks for testing, Albert. Yes, 3.9 won't work unfortunately.Regards, stevens68Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Albert ten Oever <notifications@github.com> Datum: 25.02.21  10:41  (GMT+01:00) An: stevens68/twixtbot-ui <twixtbot-ui@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [stevens68/twixtbot-ui] Missing dependencies in requirements.txt (#5) 
Sorry. My mistake. Messed up python 3.8 and 3.9 running parallel...
