### ISSUE TITLE
Add "redo" button

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#59]
Allow "redo". After loading a game, you want to analyse it by replaying the game. Currently, you can do "undo" move back one turn. But after that, it isn't possible to "redo" the move ("play forward").

Description:
- After "undo", the move that is "undone" must be added to the "redo" steps;
- After "redo", the last move added to the "redo" steps is executed again;
- After any other move (bot/manual play), the "redo" steps are discarded.

**Comment by stevens68** [comment]
nice, compact implementation. Will merge it later this week after I have switched to my new notebook.

Thanks for another contribution!

**Comment by stevens68** [comment]
Implemented in PR#60
Thanks for implemeting this! 

(removed "disable" as we don't have it for other buttons either; not sure if it's too much "blinking" if we have it for all buttons.)
