### ISSUE TITLE
Heatmap is not entirely cleared between turns

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#63]
If the heatmap feature is on, and the player plays a move from the heatmap, the heatmap drawing is not cleared after placing the move.

Reproduced by:
- Start Twixtbit
- Turn on heatmap
- Play L12

What I see: all heatmap positions for the first AND second move are shown.
Expected to see: only heatmap for second move.

NB: Turn off & on the heatmap to see the actual heatmap for the second move.

#bug

**Comment by genmeblog** [comment]
Confirmed! Just wanted to create an issue :)

**Comment by stevens68** [comment]
Fixed in PR#64
