### ISSUE TITLE
Unnecessary packages in requirements.txt

### ISSUE THREAD

**Issue by agtoever** [stevens68/twixtbot-ui#66]
In requirements.txt, there are two lines related to mysql:

    ./requirements.txt:mysqlclient==2.0.1
    ./requirements.txt:sqlparse==0.4.1

As far as I can see, these modules aren't used or needed. Additionally, these two modules require three(!) extra (Linux) packages to be installed (`python3-dev default-libmysqlclient-dev build-essential`). Removing these modules will make installing twixtbot-ui a lot easier...

Additionally, I can't find any of the following packages in any of the python files in the `/src` directory - so I suggest they are deleted from the `requirements.txt`:

- pyinstaller-hooks-contrib
- tensorboard
- idna
- tensorflow-estimator
- postpy2
- werkzeug
- beautifulsoup4
- soupsieve
- protobuf
- progress-timer
- pyasn1-modules
- django-tinymce4-lite
- rsa
- mysqlclient
- importlib-metadata
- python-magic
- requests
- bs4
- astunparse
- google-pasta
- graphics
- flatbuffers
- markdown
- sqlparse
- gast
- future
- google-auth
- python-dateutil
- urllib3
- h5py
- pyparsing
- oauthlib
- asgiref
- termcolor
- zipp
- cachetools
- requests-oauthlib
- grpcio
- cycler
- certifi
- wrapt
- pyasn1
- pefile
- django
- pyinstaller
- python-utils
- altgraph
- google-auth-oauthlib
- keras-preprocessing
- libmagic
- tensorboard-plugin-wit
- absl-py
- opt-einsum
- kiwisolver
- jsmin
- chardet
- typing-extensions
- pytz
- pywin32-ctypes
- pillow

**Comment by stevens68** [comment]
Thanks for the hint, agtoever! Removed all the trash and adjusted README.md in PR#67.
Closing this issue.
