### ISSUE TITLE
starred expression throws a syntax error - python 3.9.4

### ISSUE THREAD

**Issue by genmeblog** [stevens68/twixtbot-ui#74]
After [this](https://github.com/stevens68/twixtbot-ui/commit/60d4122f66708c8f30d83471741a2eb3e0d86f6a) change I'm getting an exception with Python 3.9.4:

```
$ python3 tbui.py
Traceback (most recent call last):
  File "/home/.../src/twixtbot-ui/src/tbui.py", line 14, in <module>
    import files as fi
  File "/home/.../src/twixtbot-ui/src/files.py", line 217
    return (*parse_tsgf_file(content)), enable_crossing_lines
            ^
SyntaxError: can't use starred expression here
```

**Comment by genmeblog** [comment]
removing parentheses helps

**Comment by agtoever** [comment]
Indeed. My pull request #73 didn't include parenthesis. @steven68 added them, but afaik they shouldn't be there...

**Comment by stevens68** [comment]
Without brackets it didn't work with Python 3.6
Python 3.9 is not yet supported (see README.md), i.e. we do no syntax checks with github workflows.

**Comment by genmeblog** [comment]
Thanks for clarifying this. Well, that Python... (minor version change brings syntax change, wtf?)

**Comment by stevens68** [comment]
... going forward I'd like to support 3.9 as well.  I will look into it. Maybe agtoever's suggestion will work for all 4 versions.
