### ISSUE TITLE
program crashes eventually (MCTS)

### ISSUE THREAD

**Issue by stevens68** [stevens68/twixtbot-ui#79]
program sometimes crashes after MCTS calculation;
picked move is already occupied.

**Comment by agtoever** [comment]
Do you have a saved game and settings file that consistently reproduces this bug? That would be great!

**Comment by stevens68** [comment]
Didn't manage to reproduce it. 
One example for such an invalid move is g9, [c7, 'swap', d6, k8, h11, g9, i8]

**Comment by stevens68** [comment]
fixed in PR#84
