### ISSUE TITLE
No module named 'tkinter' - readme update

### ISSUE THREAD

**Issue by genmeblog** [stevens68/twixtbot-ui#95]
I've just followed installing instruction on the fresh Ubuntu and found out above error. when running `tbui.py`.
It's worth to add that `python3-tk` (Debian/Ubuntu) or `python3-tkinter` (RPM based) should be installed before running the app.

https://stackoverflow.com/questions/36327134/matplotlib-error-no-module-named-tkinter

**Comment by stevens68** [comment]
Thanks for the info. I'll update the README.md
